# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa6f98f42f7a91b1b7f3058179333a0959cc8658410c0c8947844e83576dd7370f224887fa40200006f50c1e72909cab34c852558d11e5daefec60f9b1a674a0

test:
  secret_key_base: 5fbcdbe6f820967cd233dafc8701a8a12b687e486c86c0f0019310e31e5d32c6fd080e4b1f4a45bd200dc435103b6a8c3276695dbc2d3f1e3ff24496d8dcdc79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
